plank:
  job_url_prefix_config:
    '*': "https://prow.maistra.io/view/gcs/"
  default_decoration_configs:
    '*':
      timeout: 2h
      grace_period: 15s
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20200117-c08038c1c"
        initupload: "gcr.io/k8s-prow/initupload:v20200117-c08038c1c"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20200117-c08038c1c"
        sidecar: "gcr.io/k8s-prow/sidecar:v20200117-c08038c1c"
      gcs_configuration:
        path_strategy: explicit
        bucket: "maistra-prow-testing"
      gcs_credentials_secret: "gcs-credentials"
