plank:
  job_url_prefix_config:
    '*': "https://prow.maistra.io/view/"
  default_decoration_configs:
    '*':
      timeout: 4h
      grace_period: 15s
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20201207-229d6b4c8d"
        initupload: "gcr.io/k8s-prow/initupload:v20201207-229d6b4c8d"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20201207-229d6b4c8d"
        sidecar: "gcr.io/k8s-prow/sidecar:v20201207-229d6b4c8d"
      gcs_configuration:
        path_strategy: explicit
        bucket: "maistra-prow-testing"
      gcs_credentials_secret: "gcs-credentials"
