plank:
  job_url_prefix_config:
    '*': "https://prow.maistra.io/view/"
  default_decoration_configs:
    '*':
      timeout: 4h
      grace_period: 15s
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20210531-03cf33ddeb"
        initupload: "gcr.io/k8s-prow/initupload:v20210531-03cf33ddeb"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20210531-03cf33ddeb"
        sidecar: "gcr.io/k8s-prow/sidecar:v20210531-03cf33ddeb"
      gcs_configuration:
        path_strategy: explicit
        bucket: "maistra-prow-testing"
      gcs_credentials_secret: "gcs-credentials"
  pod_unscheduled_timeout: 6h
  pod_pending_timeout: 6h
