presubmits:
  Maistra/maistra.github.io:
  - name: lint
    decorate: true
    always_run: true
    skip_report: false
    branches:
      - maistra-1.2
      - maistra-1.1
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.1"
        command:
        - make
        - lint
    trigger: "(?m)^/test lint"
    rerun_command: "/test lint"
  - name: check-links
    decorate: true
    always_run: true
    skip_report: false
    branches:
      - maistra-1.2
      - maistra-1.1
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.1"
        command:
        - make
        - check-links
    trigger: "(?m)^/test check-links"
    rerun_command: "/test check-links"
  Maistra/istio-operator:
  - name: unittests
    decorate: true
    always_run: true
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    branches:
      - maistra-1.1
      - maistra-1.2
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.1"
        command:
        - make
        - compile
        - test
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
  - name: gen-check
    decorate: true
    always_run: true
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    branches:
      - maistra-1.1
      - maistra-1.2
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.1"
        command:
        - make
        - gen-check
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
  Maistra/test-infra:
  - name: lint
    decorate: true
    always_run: true
    path_alias: github.com/maistra/test-infra
    skip_report: false
    branches:
      - master
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.2"
        command:
        - make
        - lint
  - name: gen-check
    decorate: true
    always_run: true
    path_alias: github.com/maistra/test-infra
    skip_report: false
    branches:
      - master
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.2"
        command:
        - make
        - gen-check
  - name: build-containers
    decorate: true
    path_alias: github.com/maistra/test-infra
    skip_report: false
    run_if_changed: '^docker/'
    branches:
      - master
    max_concurrency: 1
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.2"
        imagePullPolicy: Always
        command:
        - entrypoint
        - make
        - build-containers
        securityContext:
          privileged: true
  Maistra/istio:
  - name: unittests
    decorate: true
    always_run: true
    path_alias: istio.io/istio
    skip_report: false
    branches:
      - maistra-1.1
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.1"
        command:
        - make
        - init
        - test
        env:
        - name: GOFLAGS
          value: -mod=vendor
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache

  Maistra/rpm-ior:
  - name: tests
    decorate: true
    always_run: true
    path_alias: maistra.io/rpm-ior
    skip_report: false
    branches:
      - maistra-1.2
      # Allow for testing
      - playground
    labels:
      preset-copr: "true"
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.2"
        imagePullPolicy: Always
        command:
        - make
        - test

  Maistra/rpm-istio-operator:
  - name: tests
    decorate: true
    always_run: true
    path_alias: maistra.io/rpm-istio-operator
    skip_report: false
    branches:
      - maistra-1.2
      # Allow for testing
      - playground
    labels:
      preset-copr: "true"
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.2"
        imagePullPolicy: Always
        command:
        - make
        - test

## The presubmits below are for the maistra-prow-testing org, which is our test bed
  maistra-prow-testing/test-infra:
  - name: build-containers
    decorate: true
    always_run: true
    path_alias: github.com/maistra/test-infra
    skip_report: false
    branches:
      - master
    max_concurrency: 1
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.2"
        imagePullPolicy: Always
        command:
        - entrypoint
        - make
        - maistra-builder
        securityContext:
          privileged: true
  maistra-prow-testing/istio-operator:
  - name: unittests
    decorate: true
    always_run: true
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    branches:
      - maistra-1.1
      - maistra-1.2
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.1"
        command:
        - make
        - test
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
  - name: gen-check
    decorate: true
    always_run: true
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    branches:
      - maistra-1.1
      - maistra-1.2
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.1"
        command:
        - make
        - gen-check
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
  maistra-prow-testing/istio:
  - name: unittests
    decorate: true
    always_run: true
    path_alias: istio.io/istio
    skip_report: false
    branches:
      - maistra-1.0
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.0"
        command:
        - make
        - init
        - test
        env:
        - name: ISTIO_BUILD_BUCKET
          value: "maistra-prow-testing"
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
  - name: integrationtests
    decorate: true
    always_run: true
    path_alias: istio.io/istio
    skip_report: false
    branches:
      - maistra-1.0
    spec:
      containers:
      - image: "quay.io/maistra/maistra-builder:1.0"
        command:
        - make
        - init
        - test.integration.local
        env:
        - name: ISTIO_BUILD_BUCKET
          value: "maistra-prow-testing"
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
