presets:
- labels:
    preset-prow-deployer: "true"
  env:
  - name: KUBECONFIG
    value: /creds/kubeconfig.yaml
  volumeMounts:
  - name: creds
    mountPath: /creds
    readOnly: true
  volumes:
  - name: creds
    secret:
      secretName: prow-deployer-kubeconfig

- labels:
    preset-quay-pusher: "true"
  env:
  - name: DOCKER_CONFIG
    value: /creds/
  volumeMounts:
  - name: creds
    mountPath: /creds
    readOnly: true
  volumes:
  - name: creds
    secret:
      secretName: quay-pusher-dockercfg

- labels:
    preset-github: "true"
  env:
  volumeMounts:
  - name: creds-github
    mountPath: /creds-github
    readOnly: true
  volumes:
  - name: creds-github
    secret:
      secretName: github-token

- labels:
    preset-copr: "true"
  env:
  - name: DEV_MODE
    value: "1"
  - name: COPR_CONFIG
    value: /creds-copr/copr
  volumeMounts:
  - name: creds-copr
    mountPath: /creds-copr
    readOnly: true
  volumes:
  - name: creds-copr
    secret:
      secretName: copr
