presets:
- labels:
    preset-prow-deployer: "true"
  env:
  - name: KUBECONFIG
    value: /creds/kubeconfig.yaml
  volumeMounts:
  - name: creds
    mountPath: /creds
    readOnly: true
  volumes:
  - name: creds
    secret:
      secretName: prow-deployer-kubeconfig

- labels:
    preset-quay-pusher: "true"
  env:
  - name: DOCKER_CONFIG
    value: /creds/
  - name: HUB
    value: quay.io/maistra-dev
  volumeMounts:
  - name: creds
    mountPath: /creds
    readOnly: true
  volumes:
  - name: creds
    secret:
      secretName: quay-pusher-dockercfg

- labels:
    preset-github: "true"
  env:
  volumeMounts:
  - name: creds-github
    mountPath: /creds-github
    readOnly: true
  volumes:
  - name: creds-github
    secret:
      secretName: github-token

- labels:
    preset-copr: "true"
  env:
  - name: DEV_MODE
    value: "1"
  - name: COPR_CONFIG
    value: /creds-copr/copr
  volumeMounts:
  - name: creds-copr
    mountPath: /creds-copr
    readOnly: true
  volumes:
  - name: creds-copr
    secret:
      secretName: copr

- labels:
    preset-gcs: "true"
  env:
  - name: GCS_PROJECT
    value: "maistra-prow-testing"
  - name: ARTIFACTS_GCS_PATH
    value: "gs://maistra-prow-testing/proxy"
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /creds-gcs/service-account.json
  volumeMounts:
  - name: creds-gcs
    mountPath: /creds-gcs
    readOnly: true
  volumes:
  - name: creds-gcs
    secret:
      secretName: gcs-credentials

- labels:
    preset-aws: "true"
  env:
  - name: AWS_DEFAULT_PROFILE
    valueFrom:
      secretKeyRef:
        name: aws
        key: AWS_DEFAULT_PROFILE
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: aws
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: aws
        key: AWS_SECRET_ACCESS_KEY
  - name: OCP_PULL_SECRET
    valueFrom:
      secretKeyRef:
        name: aws
        key: OCP_PULL_SECRET
  - name: QUAY_PULL_SECRET
    valueFrom:
      secretKeyRef:
        name: aws
        key: QUAY_PULL_SECRET
