github_reporter:
  job_types_to_report:
  - presubmit
  - postsubmit

tide:
  merge_label: "don't squash"
  merge_method:
    maistra: squash
  target_url: https://prow.maistra.io/tide
  context_options:
    from-branch-protection: true

  queries:

  - repos:
    - maistra/rpm-common
    - maistra/rpm-ior
    - maistra/rpm-istio-operator
    - maistra/test-infra
    - maistra/proxy
    - maistra/envoy
    - maistra/istio
    labels:
    - "okay to merge"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    reviewApprovedRequired: true

  - repos:
    - maistra/rpm-ior
    - maistra/rpm-istio-operator
    - maistra/proxy
    - maistra/istio
    author: maistra-bot
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    labels:
    - auto-merge
    reviewApprovedRequired: false
