github_reporter:
  job_types_to_report:
  - presubmit
  - postsubmit

tide:
  merge_method:
    Maistra: squash
  target_url: https://prow.maistra.io/tide

  queries:

  - repos:
    - Maistra/rpm-ior
    - Maistra/rpm-istio-operator
    - Maistra/test-infra
    labels:
    - "okay to merge"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    reviewApprovedRequired: true

  - repos:
    - Maistra/rpm-ior
    - Maistra/rpm-istio-operator
    author: maistra-bot
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    labels:
    - auto-merge
    reviewApprovedRequired: false
