apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-gcsweb
  namespace: gcs
spec:
  acme:
    email: jwendell@redhat.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-gcsweb
    solvers:
    - http01:
        ingress:
          class: nginx
